name: Frontend CI/CD

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker image build
        run: |
          docker build \
            --build-arg VITE_KAKAO_MAP_KEY=${{ secrets.VITE_KAKAO_MAP_KEY }} \
            --build-arg VITE_KAKAO_CLIENT_ID=${{ secrets.VITE_KAKAO_CLIENT_ID }} \
            --build-arg VITE_TOSS_CLIENT_KEY=${{ secrets.VITE_TOSS_CLIENT_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/budong-frontend .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/budong-frontend

  deploy-to-ec2:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/budong-frontend

      - name: Create .env file
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
          echo "CHAT_SERVER=${{ secrets.CHAT_SERVER }}" >> .env

      - name: Docker Compose Down
        run: sudo docker-compose -p budong-frontend down

      - name: Docker Compose Up
        run: sudo docker-compose -p budong-frontend up -d
